basePath: /api/
definitions:
  atelino_internal_dto.CreateHitokotoRequest:
    properties:
      content:
        type: string
    required:
    - content
    type: object
  atelino_internal_dto.HitokotoIDRequest:
    properties:
      id:
        minimum: 1
        type: integer
    required:
    - id
    type: object
  atelino_internal_dto.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: Atelino 后端 API 文档
  termsOfService: http://swagger.io/terms/
  title: Atelino API
  version: 1.0.1
paths:
  /hitokoto:
    post:
      consumes:
      - application/json
      description: 创建一条新的一言记录。如果内容已存在，则返回 409 冲突错误；其他数据库异常返回 500。
      parameters:
      - description: 一言内容
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/atelino_internal_dto.CreateHitokotoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 添加成功
          schema:
            allOf:
            - $ref: '#/definitions/atelino_internal_dto.Response'
            - properties:
                code:
                  type: integer
                data:
                  $ref: '#/definitions/atelino_internal_dto.HitokotoIDRequest'
                message:
                  type: string
              type: object
        "400":
          description: 请求参数错误
          schema:
            allOf:
            - $ref: '#/definitions/atelino_internal_dto.Response'
            - properties:
                code:
                  type: integer
                message:
                  type: string
              type: object
        "409":
          description: 该一言已存在
          schema:
            allOf:
            - $ref: '#/definitions/atelino_internal_dto.Response'
            - properties:
                code:
                  type: integer
                message:
                  type: string
              type: object
        "500":
          description: 数据库错误
          schema:
            allOf:
            - $ref: '#/definitions/atelino_internal_dto.Response'
            - properties:
                code:
                  type: integer
                message:
                  type: string
              type: object
      security:
      - BearerAuth: []
      summary: 添加一言
      tags:
      - 一言
  /hitokoto/{id}:
    delete:
      consumes:
      - application/json
      description: 传入一言的 ID，从数据库中删除对应的记录。若 ID 不存在则返回 404，数据库异常则返回 500。
      parameters:
      - description: 一言 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 删除成功
          schema:
            allOf:
            - $ref: '#/definitions/atelino_internal_dto.Response'
            - properties:
                code:
                  type: integer
                message:
                  type: string
              type: object
        "400":
          description: 请求参数错误
          schema:
            allOf:
            - $ref: '#/definitions/atelino_internal_dto.Response'
            - properties:
                code:
                  type: integer
                message:
                  type: string
              type: object
        "401":
          description: 未授权
          schema:
            allOf:
            - $ref: '#/definitions/atelino_internal_dto.Response'
            - properties:
                code:
                  type: integer
                message:
                  type: string
              type: object
        "404":
          description: 没有找到对应的一言
          schema:
            allOf:
            - $ref: '#/definitions/atelino_internal_dto.Response'
            - properties:
                code:
                  type: integer
                message:
                  type: string
              type: object
        "500":
          description: 数据库错误
          schema:
            allOf:
            - $ref: '#/definitions/atelino_internal_dto.Response'
            - properties:
                code:
                  type: integer
                message:
                  type: string
              type: object
      security:
      - BearerAuth: []
      summary: 删除一言
      tags:
      - 一言
securityDefinitions:
  BearerAuth:
    type: basic
swagger: "2.0"
